id: fi--ratelimit
version: 1.0.0
platforms: 
  - EUMETSAT
  - ECMWF
routes:
  - route:
      id: fi/ratelimit/edr
      endpoint: https://opendata.fmi.fi/edr
      ratelimitAuth:
        requestRate:
          rate: 10
          burst: 20
        quota:
          count: 100
          time_window: 300
      ratelimitAnon:
        requestRate:
          rate: 1
          burst: 5
        quota:
          count: 50
          time_window: 300
      cors: true
