id: jeremy 
version: 1.0.0
platforms: 
  - EUMETSAT
  - ECMWF
routes:
  - route:
      id: jeremy/edr <-- choose route
      endpoint: https://api.dataplatform.knmi.nl/edr/v1
      cors: true
      apikey:
        headerParam: 'authorization'
        secretName: eyJvcmciOiI1ZTU1NGUxOTI3NGE5NjAwMDEyYTNlYjEiLCJpZCI6IjAwZGZlMDY4ZTk4MjRkZjY4Njg5ODVkMDhlZWY4ZDMwIiwiaCI6Im11cm11cjEyOCJ9
