id: fi-fmi-edr
version: 1.0.0
platforms: 
  - EUMETSAT
  - ECMWF
routes:
  - route:
      id: fi-fmi-edr
      endpoint: https://opendata.fmi.fi/edr
      ratelimitAnon:
        requestRate:
          rate: 10
          burst: 20
        quota:
          count: 50
          time_window: 3600
      ratelimitAuth:
        requestRate:
          rate: 60
          burst: 100
        quota:
          count: 500
          time_window: 3600
      apikey:
        headerParam: 'Authorization'
        secretName: FI-FMI-EDR-KEY
      cors: true
